name: Deploy Go App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > pem_file.pem
          chmod 600 pem_file.pem

      - name: Deploy Go app to EC2
        run: |
          ssh -i pem_file.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/savina-stock-api

            # Parar e remover o container Docker atual do Go
            docker stop go-app || true
            docker rm go-app || true

            # Puxar as últimas alterações do repositório
            git pull origin main

            # Build da nova imagem Docker da aplicação Go
            docker build -t go-app -f Dockerfile .

            # Rodar o novo container Docker da aplicação Go com variáveis de ambiente
            docker run -d --restart always -p 8080:8080 \
              -e DB_HOST="${{ secrets.DB_HOST }}" \
              -e DB_USER="${{ secrets.DB_USER }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e DB_NAME="${{ secrets.DB_NAME }}" \
              -e DB_PORT="${{ secrets.DB_PORT }}" \
              -e SERVER_PORT="${{ secrets.SERVER_PORT }}" \
              -e CLOUDINARY_CLOUD_NAME="${{ secrets.CLOUDINARY_CLOUD_NAME }}" \
              -e CLOUDINARY_API_KEY="${{ secrets.CLOUDINARY_API_KEY }}" \
              -e CLOUDINARY_API_SECRET="${{ secrets.CLOUDINARY_API_SECRET }}" \
              -e AWS_REGION="${{ secrets.AWS_REGION }}" \
              -e AWS_BUCKET_NAME="${{ secrets.AWS_BUCKET_NAME }}" \
              -e AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}" \
              -e AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
              -e HOST_WEB="${{ secrets.HOST_WEB }}" \
              --name go-app go-app

            docker system prune -af
          EOF
