name: Deploy Go App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add SSH key
        run: |
          echo "${{ secrets.EC2_PEM_KEY }}" > pem_file.pem
          chmod 600 pem_file.pem

      - name: Deploy Go app to EC2
        run: |
          ssh -i pem_file.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /var/www/savina-stock-api

            # Parar e remover o container Docker atual do Go
            docker stop go-app || true
            docker rm go-app || true

            # Puxar as últimas alterações do repositório
            git pull origin main

            # Build da nova imagem Docker da aplicação Go
            docker build -t go-app -f Dockerfile .

            # Rodar o novo container Docker da aplicação Go
            docker run -d -p 8080:8080 --name go-app go-app
          EOF
